# GR-1 Observation Viewer

This notebook allows you to view and analyze a single GR-1 observation pkl file.


In [1]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


In [ ]:
# Set the path to your observation pkl file
pkl_file = "/virtual_lab/sjw_alinlab/beomjun/Isaac-GR00T/output/gr1_new/nvidia_GR00T-N1.5-3B/gr1_unified/PnPBottleToCabinetClose_GR1ArmsAndWaistFourierHands_Env/observations/episode_0_env_0.pkl"

In [12]:
# Load the observation file
with open(pkl_file, 'rb') as f:
    obs = pickle.load(f)
print(f"Loaded observation file: {pkl_file}")
print(f"Type: {type(obs)}")
print(f"Length: {len(obs)} steps")


Loaded observation file: /virtual_lab/sjw_alinlab/beomjun/Isaac-GR00T/output/gr1_new/nvidia_GR00T-N1.5-3B/gr1_unified/PnPBottleToCabinetClose_GR1ArmsAndWaistFourierHands_Env/observations/episode_0_env_0.pkl
Type: <class 'list'>
Length: 80 steps


In [21]:
obs[0].keys()

dict_keys(['annotation.human.coarse_action', 'state.left_arm', 'state.left_hand', 'state.right_arm', 'state.right_hand', 'state.waist', 'video.ego_view_bg_crop_pad_res256_freq20', 'video.ego_view_pad_res256_freq20'])

In [22]:
obs[0]['annotation.human.coarse_action']

'unlocked_waist: pick up the bottled water, place it into the cabinet and close the cabinet'

In [ ]:
obs[0]['state.left_arm'] # 팔꿈치인듯

array([[[ 0.01200677,  0.08859215,  0.04272151, -2.1       ,
         -0.00420572, -0.02216337,  0.01682124]]], dtype=float32)

In [ ]:
obs[0]['state.left_hand'] # 손목 (End effector!)

array([[[0.00541653, 0.00082331, 0.00038404, 0.00028711, 0.00277082,
         0.00195512]]], dtype=float32)

In [ ]:
obs[0]['state.waist'] # 허리

array([[[-0.03146506, -0.01350786, -0.03799334]]], dtype=float32)